# test:
# path: /test/{age}
#controller: App\Controller\TestController::index
#  methods: [GET, POST]
#  host: localhost
#  schemes: [https, http]
#  defaults:
#    age: 0
#  requirements:
#    age: \d+
